language: node_js
node_js:
  - stable
  - '8'  # Recommended deploy version
branches:
  only:
    - master
    - develop
before_install:
  - npm i -g npm@6.9.0
  - npm i -g firebase-tools
script:
  - cd functions
  - npm install
  - npm run lint
  - npm run test
  - cd ..
deploy:
  - provider: firebase
    project: dev
    skip_cleanup: true
    on:
      branch: develop
      repo: drexelieee/dragonhacks-backend
      node: '8'
  - provider: firebase
    project: prod
    skip_cleanup: true
    on:
      branch: master
      repo: drexelieee/dragonhacks-backend
      node: '8'
