language: node_js
node_js:
  - stable
  - '8'
branches:
  only:
    - master
    - develop
before_install:
  - npm i -g npm@6.9.0
  - npm i -g firebase-tools
script:
  - cd functions
  - npm install
  - npm run lint
  - npm run test
  - cd ..
deploy:
  - provider: firebase
    token:
      secure: 'yDsfiI8FhNzYrqVLi9VDhtQkOA14XTpGvl08EZNPqcXG92OXwD+Uq0ArQ1T9ukT4KoWOychYJRRa2semmVGkm3gRAmWM9kSlgKIFCIySTvmyfzjL9fmZbjkN7s5IZLz7S0s2/YbZ8J03BjLYF0AjduGji/n13OJRC1mdiqii9pRhnmduw93oRWyyqnDZIgNfV1dL8Tb8aBYguqrI2uGqL5VH+1U/zMgJYUlaBDWMeyrp9/fKu4H4mQWrDg7F0j/ps5/YB+8FRXq0dE73n+rLTd7PR3gDg8u//pwmHy+A109xlAw8N0z7DDOWIRlw6ssBCXfZUFJomeT92+E93HaNbMIe/4nLeu4bWXOjg/ScH0zyC3FB0lKogT+ABd/4Nnv40kDwUTWjtUIUxZg8kUCwRJdensqFPngzMn7YOhCPUWxED3VAyNiE6sb14nBM0MjII2REmwyreakeLzJk2kMhWmG7IVX5i2Pu1zYVN9X0iZJ9LzvFtzdw7SmpiRcAslB/6ZMhDd8H532Nk2AoiX0nyIJKAKhK4QUAOq8D9gW6aEcNR0obE/ZQFpY1ZZHDN8skNpZmILTUjnWY+bw06GD/WZRqT1zZYlcZ6DVah5Q6oLH3XYh3xuZ3x1b8F0GF3fkty7h6I3ZRO9n2wRvp/x38e+9JjdmglpaBOA0Ao+1ARcA='
    project: develop
    on:
      branch: develop
      repo: drexelieee/dragonhacks-backend
      node: stable
  - provider: firebase
    token:
      secure: 'jPUXTql/ozug7sjDO3F5nrRC8vWpq9iIl0yvQbnShvytLDPEGuNMf/VV5zCOqrzBy7OquztXx9aFR6TPSGek8DfIp9B0rCV8XrrIzt+sK1GOLoRGQua8NXugcKzmxjYRM5HyvBEUbTBLJOrZlp6YMJ4Dcf1R0qepbP2QeaXwIcm5NwraPr7E90R6FfHk0IEXPRH1Nkj6dS0H8ee5aOF43GMzmfyWIFmQkfyOkBeP/90HD+3+pOgj6UJn1l0OlFAYmbrDHePkRDdK/aWLumCBZV5a52q5pnw8Qo1a2+8acKHZfXdKAsxf8AQPxRsRxTGq9XbG9Y0aSYTdXKRPIJt/+Isfvnb4xHY1wb7vouqCXmjB4jxixhmTGgmdG6aJQUKQjIalWF1bv0riaLS91CYD22B7le3z1UE8zMMSbO6UJ3bIrPfV79ZTbzsX6bsRjEKZNI0BuGpGeZ2MgpkUWtJegIi9S9JzqMFZFl/DznMcXW0ekMHkJByNICg93SRUzyrpug8KUANmm40L6dpATczD/po+ulQV8wHiPKAEiFazJLDKS8Mr8YxPwYo0hcLqomt5Hg9WHH2GYcHGSnz04RnQT+RIcITZ7hdvdE4xbjnJPqOzKF3KI8Ii4JZ4vcrQQz1KB8/GzdJXOmHSPD1J0I0jJcYugAw74a4b1lpIadTWjdc='
    project: prod
    on:
      branch: master
      repo: drexelieee/dragonhacks-backend
      node: stable
